
test:
	../LR_FusionInspector_to_ORF.py --genome FI/IGV_inputs/finspector.fa --bam FI/IGV_inputs/finspector.junction_reads.bam --gtf FI/IGV_inputs/finspector.gtf --fusions_tsv FI/finspector.FusionInspector.fusions.abridged.tsv


clean:
	rm -rf ./LR_FusionInspector_to_ORF_outdir
